services:
    db:
        image: postgres:12.8
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: botletics
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:6.2.6

volumes:
    postgres-data:
        driver: local
