services:
    db:
        image: postgres:14.0
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: botletics
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        driver: local
