name: Deploy db-query

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - servers/lambdas/db-query/**
      - servers/server/prisma/**

defaults:
  run:
    shell: bash

jobs:
  buildAndPushImage:
    uses: maxsynnott/botletics/.github/workflows/buildAndPushImage.yml@master
    with:
      ecrRepositoryName: db-query
      directoryPath: ./servers/lambdas/db-query
      copyPrismaDirectory: true
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
      dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerHubAccessToken: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  updateLambdaImageUri:
    needs: buildAndPushImage
    uses: maxsynnott/botletics/.github/workflows/updateLambdaImageUri.yml@master
    with:
      ecrRepositoryName: db-query
      lambdaFunctionName: db-query
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
