name: Deploy migrator

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - servers/lambdas/migrator/**
      - servers/server/prisma/**

defaults:
  run:
    shell: bash

jobs:
  buildAndPushImage:
    uses: maxsynnott/botletics/.github/workflows/buildAndPushImage.yml@master
    with:
      ecrRepositoryName: botletics-db-migrator
      directoryPath: ./servers/lambdas/migrator
      copyPrismaDirectory: true
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
      dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerHubAccessToken: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  updateLambdaImageUri:
    needs: buildAndPushImage
    uses: maxsynnott/botletics/.github/workflows/updateLambdaImageUri.yml@master
    with:
      ecrRepositoryName: botletics-db-migrator
      lambdaFunctionName: botletics-migrator
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
