# TODO: This should be replaced either by server endpoint or code

name: Deploy random-bot

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - bots/chess/random/**

defaults:
  run:
    shell: bash

jobs:
  buildAndPushImage:
    uses: maxsynnott/botletics/.github/workflows/buildAndPushImage.yml@master
    with:
      ecrRepositoryName: random-bot
      directoryPath: ./bots/chess/random
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
      dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerHubAccessToken: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  updateLambdaImageUri:
    needs: buildAndPushImage
    uses: maxsynnott/botletics/.github/workflows/updateLambdaImageUri.yml@master
    with:
      ecrRepositoryName: random-bot
      lambdaFunctionName: random-bot
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
