name: Migrate

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Deploy migrator"]
    types:
      - completed

env:
  AWS_REGION: ap-southeast-1

defaults:
  run:
    shell: bash

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Migrate
        run: aws lambda invoke --function-name botletics-migrator /dev/stdout
