name: Terraform apply

on:
  workflow_call:
    inputs:
      awsRegion:
        type: string
        required: false
        default: ap-southeast-1
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretKey:
        required: true

env:
  IMAGE_TAG: latest
  AWS_REGION: ap-southeast-1

defaults:
  run:
    shell: bash

jobs:
  terraformApply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretKey }}
          aws-region: ${{ inputs.awsRegion }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate -no-color

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
